"""The Feature Registry contents.

This is where we "reserve all features" -- not as empty fields, but as full
contracts (representation, unit, dependencies, producer, fidelity levels,
conservation constraints, uncertainty, valid range, validation, status).

Filling in a feature later means: implement its producer module, raise its
``status`` from RESERVED -> IMPLEMENTED -> CALIBRATED -> VALIDATED.  The pipeline
already runs with stubs in place.
"""
from __future__ import annotations

from aevum.core.registry import FeatureRegistry, FeatureSpec, Representation, Status

SF = Representation.SCALAR_FIELD
VF = Representation.VECTOR_FIELD
NET = Representation.NETWORK
OBJ = Representation.OBJECT_SET
EVT = Representation.EVENT_STREAM
GS = Representation.GLOBAL_SCALAR

R = Status.RESERVED
I = Status.IMPLEMENTED


def _f(*args, **kwargs) -> FeatureSpec:
    return FeatureSpec(*args, **kwargs)


def build_registry() -> FeatureRegistry:
    reg = FeatureRegistry()
    reg.register_many([
        # ---------------- stellar & orbit ----------------
        _f("stellar.luminosity", GS, "global", "W", "stellar",
           time_support="instantaneous", fidelity_levels=["analytic", "tracks"],
           valid_range=[1e23, 1e28], status=I,
           validation="faint-young-sun: L(t) monotonic for main sequence",
           description="Bolometric stellar luminosity at time t."),
        _f("stellar.surface_flux", SF, "surface_cells", "W m^-2", "stellar",
           dependencies=["stellar.luminosity"],
           time_support="annual_mean", fidelity_levels=["analytic"], status=I,
           conservation_constraints=["energy"],
           valid_range=[0.0, 4000.0],
           validation="global mean ~= L/(16 pi d^2)",
           description="Top-of-atmosphere insolation, latitude & obliquity weighted."),
        _f("stellar.mean_flux", GS, "global", "W m^-2", "stellar",
           dependencies=["stellar.luminosity", "orbit.eccentricity"],
           time_support="annual_mean", fidelity_levels=["analytic"], status=I,
           conservation_constraints=["energy"],
           valid_range=[0.0, 4000.0],
           validation="area-weighted mean of stellar.surface_flux"),
        _f("orbit.obliquity", GS, "global", "deg", "stellar",
           fidelity_levels=["fixed", "perturbed"], valid_range=[0.0, 90.0], status=I),
        _f("orbit.eccentricity", GS, "global", "1", "stellar",
           fidelity_levels=["fixed", "perturbed"], valid_range=[0.0, 0.8], status=I),
        _f("orbit.eccentricity_factor", GS, "global", "1", "stellar",
           dependencies=["orbit.eccentricity"],
           fidelity_levels=["analytic"], valid_range=[1.0, 3.5], status=I,
           description="Annual-mean inverse-square forcing multiplier."),

        # ---------------- interior thermal history ----------------
        _f("interior.mantle_temperature", GS, "global", "K", "interior",
           fidelity_levels=["box", "proxy_3d"], valid_range=[1200.0, 4000.0], status=I,
           conservation_constraints=["energy"],
           validation="monotone cooling under net heat loss",
           description="Bulk mantle potential temperature."),
        _f("interior.radiogenic_heat", GS, "global", "W", "interior",
           fidelity_levels=["analytic"], valid_range=[0.0, 1e14], status=I,
           description="Decaying radiogenic heat production."),
        _f("interior.convective_heat_loss", GS, "global", "W", "interior",
           dependencies=["interior.mantle_temperature"],
           fidelity_levels=["box"], valid_range=[0.0, 2e14], status=I,
           description="Global mantle convective heat loss."),
        _f("interior.surface_heat_flow", GS, "global", "W m^-2", "interior",
           dependencies=["interior.convective_heat_loss"],
           fidelity_levels=["box"], valid_range=[0.0, 0.5], status=I,
           description="Convective heat loss divided by planetary surface area."),
        _f("interior.tectonic_vigor", GS, "global", "1", "interior",
           dependencies=["interior.mantle_temperature", "interior.convective_heat_loss"],
           fidelity_levels=["parametric"], valid_range=[0.0, 5.0], status=I,
           description="Dimensionless convective vigour driving plate speeds."),
        _f("interior.degassing_co2", GS, "global", "mol Myr^-1", "interior",
           dependencies=["interior.tectonic_vigor"],
           fidelity_levels=["parametric"], valid_range=[0.0, 1e20], status=I,
           description="Volcanic/metamorphic CO2 outgassing rate."),
        _f("mantle.heat_anomaly", SF, "surface_cells", "1", "interior",
           dependencies=["interior.mantle_temperature", "tectonics.boundaries",
                         "crust.type", "crust.age_myr", "crust.stability"],
           fidelity_levels=["low_order_proxy"], valid_range=[-1.0, 1.0],
           status=I,
           validation="R1 heat diffusion, continental insulation, and slab cooling microbenchmarks",
           description="Dimensionless low-order mantle heat anomaly projected to surface cells."),
        _f("mantle.upwelling_potential", SF, "surface_cells", "1", "interior",
           dependencies=["mantle.heat_anomaly", "tectonics.boundaries",
                         "lithosphere.thermal_thickness"],
           fidelity_levels=["low_order_proxy"], valid_range=[0.0, 1.0],
           status=I,
           description="Relative tendency for mantle upwelling from positive heat anomaly, ridges, and thin lithosphere."),
        _f("mantle.downwelling_potential", SF, "surface_cells", "1", "interior",
           dependencies=["mantle.heat_anomaly", "tectonics.boundaries", "crust.age_myr"],
           fidelity_levels=["low_order_proxy"], valid_range=[0.0, 1.0],
           status=I,
           description="Relative tendency for slab-like downwelling from trenches, old oceanic crust, and cold anomaly."),
        _f("lithosphere.thermal_thickness", SF, "surface_cells", "m", "interior",
           dependencies=["mantle.heat_anomaly", "crust.type", "crust.age_myr",
                         "crust.stability"],
           fidelity_levels=["age_heat_proxy"], valid_range=[20000.0, 260000.0],
           status=I,
           description="Thermal lithosphere thickness proxy from oceanic age, continental stability, and mantle heat."),
        _f("tectonics.rift_potential", SF, "surface_cells", "1", "interior",
           dependencies=["mantle.upwelling_potential", "lithosphere.thermal_thickness",
                         "crust.stability", "tectonics.boundaries"],
           fidelity_levels=["low_order_proxy"], valid_range=[0.0, 1.0],
           status=I,
           description="Relative tendency for continental rifting from heat, inherited weakness, margins, and sutures."),
        _f("tectonics.plume_potential", SF, "surface_cells", "1", "interior",
           dependencies=["mantle.heat_anomaly", "mantle.upwelling_potential",
                         "mantle.downwelling_potential"],
           fidelity_levels=["low_order_proxy"], valid_range=[0.0, 1.0],
           status=I,
           description="Deterministic plume trigger potential from heat and upwelling maxima."),

        # ---------------- tectonics & crust ----------------
        _f("tectonics.plate_id", SF, "surface_cells", "1", "tectonics",
           fidelity_levels=["voronoi_euler", "stress_topology"], status=I,
           validation="plates tile the sphere with no gaps/overlaps",
           description="Integer plate label per cell."),
        _f("tectonics.plate_velocity", VF, "surface_cells", "m s^-1", "tectonics",
           dependencies=["tectonics.plate_id", "interior.tectonic_vigor"],
           fidelity_levels=["euler_poles"], status=I),
        _f("crust.type", SF, "surface_cells", "1", "tectonics",
           fidelity_levels=["binary", "lithology"], status=I,
           description="0 = oceanic, 1 = continental."),
        _f("crust.thickness_m", SF, "surface_cells", "m", "tectonics",
           dependencies=["crust.type"], conservation_constraints=["crust_area"],
           fidelity_levels=["rule_based", "flexural"], valid_range=[0.0, 80000.0],
           status=I, validation="continental 25-70 km, oceanic 5-10 km"),
        _f("crust.age_myr", SF, "surface_cells", "Myr", "tectonics",
           dependencies=["tectonics.plate_id"], fidelity_levels=["advected"],
           valid_range=[0.0, 4500.0], status=I,
           description="Time since crust formed at a ridge."),
        _f("crust.origin", SF, "surface_cells", "1", "tectonics",
           dependencies=["crust.type", "tectonics.boundaries"],
           fidelity_levels=["rule_based"], valid_range=[0.0, 8.0], status=I,
           description="Crust genesis code: ridge, primordial, arc, suture, plume/impact, craton."),
        _f("crust.domain", SF, "surface_cells", "1", "tectonics",
           dependencies=["crust.type", "crust.origin", "crust.stability"],
           fidelity_levels=["object_derived"], valid_range=[0.0, 12.0], status=I,
           description="Geological domain: oceanic, craton, interior, margin, terrane, suture, LIP."),
        _f("crust.reworked_age_myr", SF, "surface_cells", "Myr", "tectonics",
           dependencies=["tectonics.boundaries"], fidelity_levels=["rule_based"],
           valid_range=[-1.0, 4500.0], status=I,
           description="Most recent tectonic reworking age, distinct from crust formation age."),
        _f("tectonics.orogeny_age_myr", SF, "surface_cells", "Myr", "tectonics",
           dependencies=["tectonics.boundaries", "crust.domain"],
           fidelity_levels=["rule_based"], valid_range=[-1.0, 4500.0],
           status=I, description="Most recent mountain-building or collision age."),
        _f("tectonics.volcanism_age_myr", SF, "surface_cells", "Myr", "tectonics",
           dependencies=["tectonics.boundaries", "crust.origin"],
           fidelity_levels=["rule_based"], valid_range=[-1.0, 4500.0],
           status=I, description="Most recent volcanic or arc-construction age."),
        _f("crust.stability", SF, "surface_cells", "1", "tectonics",
           dependencies=["crust.age_myr", "crust.type"], fidelity_levels=["proxy"],
           valid_range=[0.0, 1.0], status=I,
           description="Cratonic stability / resistance to recycling and reworking."),
        _f("tectonics.boundaries", NET, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.plate_id", "tectonics.plate_velocity"],
           fidelity_levels=["classified"], status=I,
           description="Plate boundary network classified ridge/trench/transform/suture/passive/active."),
        _f("tectonics.boundary_objects", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.boundaries"], fidelity_levels=["component_objects"],
           status=I, description="Connected ridge/trench/suture/passive/active boundary segments."),
        _f("tectonics.deformation_intensity", SF, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.boundaries", "tectonics.plate_id"],
           fidelity_levels=["deforming_network"], valid_range=[0.0, 1.0],
           status=I,
           description="Active deformation intensity separated from crust provenance."),
        _f("tectonics.deformation_style", SF, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.deformation_intensity", "tectonics.boundaries"],
           fidelity_levels=["deforming_network"], valid_range=[0.0, 8.0],
           status=I,
           description="Active deformation style: none, collision/subduction core or shoulder, rift, transform."),
        _f("tectonics.deforming_networks", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.deformation_intensity", "tectonics.deformation_style"],
           fidelity_levels=["deforming_network_objects"], status=I,
           description="Component objects for active deforming-network cores and shoulders."),
        _f("tectonics.wilson_cycles", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.boundary_objects"], fidelity_levels=["state_machine"],
           status=I, description="Reduced Wilson-cycle stage objects derived from boundary segments."),
        _f("tectonics.ocean_gateways", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.wilson_cycles", "tectonics.boundary_objects"],
           fidelity_levels=["component_objects"], status=I,
           description="Ocean gateway objects tied to Wilson-cycle opening, mature, closing, and suture phases."),
        _f("tectonics.ocean_basins", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.boundary_objects"], fidelity_levels=["lifecycle_objects"],
           status=I, description="Tectonic ocean-basin lifecycle objects from rift opening through suture."),
        _f("tectonics.rift_systems", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.boundary_objects", "tectonics.rift_potential"],
           fidelity_levels=["lifecycle_objects"], status=I,
           description="Rift and narrow-sea systems linked to opening ocean basins."),
        _f("tectonics.breakup_seaways", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.continents", "tectonics.rift_potential",
                         "tectonics.plate_topologies", "tectonics.rift_systems"],
           fidelity_levels=["mechanism_objects"], status=I,
           description="Deterministic supercontinent-breakup and multi-rift seaway corridors through weak continental lithosphere."),
        _f("tectonics.passive_margins", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.boundary_objects", "tectonics.ocean_basins"],
           fidelity_levels=["lifecycle_objects"], status=I,
           description="Passive margin lifecycle objects attached to mature ocean basins."),
        _f("tectonics.spreading_centers", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.boundary_objects", "tectonics.ocean_basins"],
           fidelity_levels=["lifecycle_objects"], status=I,
           description="Spreading-center objects linked to opening ocean basins."),
        _f("tectonics.closing_margins", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.boundary_objects", "tectonics.ocean_basins"],
           fidelity_levels=["lifecycle_objects"], status=I,
           description="Subduction and active-margin objects consuming ocean basins."),
        _f("tectonics.sutures", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.boundary_objects", "tectonics.ocean_basins"],
           fidelity_levels=["lifecycle_objects"], status=I,
           description="Suture lifecycle objects marking closed ocean basins."),
        _f("archive.wilson_cycle_phase", SF, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.wilson_cycles"],
           fidelity_levels=["phase_field"], valid_range=[0.0, 8.0], status=I,
           description="Wilson-cycle phase code: inactive, rift/opening, mature, closing, collision, suture."),
        _f("tectonics.cratons", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["crust.origin", "crust.stability"], fidelity_levels=["component_objects"],
           status=I, description="Stable continental nuclei / craton objects."),
        _f("tectonics.internal_geographic_block_id", SF, "surface_cells", "1",
           "tectonics",
           dependencies=["crust.type", "crust.domain",
                         "tectonics.continent_id"],
           fidelity_levels=["inherited_continental_block_cargo"], status=I,
           description="Stable inherited internal geographic block id for continental crust cells; ocean is 0."),
        _f("tectonics.internal_geographic_block_code", SF, "surface_cells", "1",
           "tectonics",
           dependencies=["tectonics.internal_geographic_block_id",
                         "crust.domain", "crust.stability"],
           fidelity_levels=["inherited_continental_block_cargo"],
           valid_range=[0.0, 6.0], status=I,
           description="Internal continental block class: craton core, platform, intracratonic basin, mobile belt, rifted margin, or accreted terrane."),
        _f("tectonics.internal_geographic_blocks", OBJ, "surface_cells", "1",
           "tectonics",
           dependencies=["tectonics.internal_geographic_block_id",
                         "tectonics.internal_geographic_block_code",
                         "tectonics.continent_id"],
           fidelity_levels=["inherited_continental_block_cargo"], status=I,
           description="Inherited internal continent-block objects with class, area, parent continent, and crustal summaries."),
        _f("tectonics.continent_id", SF, "surface_cells", "1", "tectonics",
           dependencies=["crust.type"], fidelity_levels=["stable_graph_components"],
           status=I, description="Stable numeric continent id for continental crust cells; ocean is -1."),
        _f("tectonics.terrane_id", SF, "surface_cells", "1", "tectonics",
           dependencies=["crust.origin", "crust.domain"], fidelity_levels=["stable_graph_components"],
           status=I, description="Stable numeric id for accreted terrane / arc fragments; non-terrane is -1."),
        _f("tectonics.continents", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.continent_id", "crust.domain"],
           fidelity_levels=["component_objects"], status=I,
           description="Continent objects with area, centroid, core fraction, margins, and width diagnostics."),
        _f("tectonics.terranes", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.terrane_id", "crust.domain"],
           fidelity_levels=["component_objects"], status=I,
           description="Accreted terrane, island-arc, and narrow suture component objects."),
        _f("tectonics.plate_topologies", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.plate_id", "tectonics.boundaries",
                         "tectonics.continent_id", "tectonics.terrane_id"],
           fidelity_levels=["resolved_topology_objects"], status=I,
           description="Resolved plate topology summaries with neighbours, shared edges, boundary load, and continental/terrane cargo."),
        _f("tectonics.continent_lifecycle_events", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.continent_id", "tectonics.terrane_id",
                         "tectonics.plate_topologies"],
           fidelity_levels=["lineage_objects"], status=I,
           description="Recent continent/terrane split, merge, and plate-label capture lineage events."),
        _f("tectonics.plumes", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["interior.tectonic_vigor", "tectonics.plume_potential"],
           fidelity_levels=["rule_based"],
           status=I, description="Mantle plume proxy objects."),
        _f("tectonics.lips", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.plumes", "crust.origin"], fidelity_levels=["rule_based"],
           status=I, description="Large igneous province objects created by plume heads."),
        _f("tectonics.plates", OBJ, "global", "1", "tectonics",
           fidelity_levels=["euler"], status=I,
           description="Plate objects with Euler pole, rate, area, type."),
        _f("tectonics.orogens", OBJ, "surface_cells", "1", "tectonics",
           dependencies=["tectonics.boundaries"], fidelity_levels=["rule_based"], status=I,
           description="Mountain belts from collision/subduction, with formation age."),
        _f("tectonics.volcanoes", OBJ, "surface_cells", "1", "tectonics",
           fidelity_levels=["rule_based"], status=I),
        _f("tectonics.regime", GS, "global", "1", "tectonics",
           dependencies=["interior.tectonic_vigor"], fidelity_levels=["state_machine"],
           status=I, description="Active tectonic mode (mobile/sluggish/episodic/stagnant)."),
        _f("tectonics.land_component_id", SF, "surface_cells", "1", "diagnostics",
           dependencies=["terrain.elevation_m", "ocean.sea_level_m"],
           fidelity_levels=["graph_components"], status=I,
           description="Connected exposed-land component id; ocean cells are -1."),
        _f("tectonics.continental_component_id", SF, "surface_cells", "1", "diagnostics",
           dependencies=["crust.type"], fidelity_levels=["graph_components"], status=I,
           description="Connected continental-crust component id; oceanic cells are -1."),
        _f("tectonics.land_width_steps", SF, "surface_cells", "graph steps", "diagnostics",
           dependencies=["terrain.elevation_m", "ocean.sea_level_m"],
           fidelity_levels=["graph_distance"], valid_range=[0.0, 1e6], status=I,
           description="Graph-distance width proxy inside exposed land."),
        _f("tectonics.continent_width_steps", SF, "surface_cells", "graph steps",
           "diagnostics", dependencies=["crust.type"],
           fidelity_levels=["graph_distance"], valid_range=[0.0, 1e6], status=I,
           description="Graph-distance width proxy inside continental crust."),
        _f("tectonics.ribbon_index", SF, "surface_cells", "1", "diagnostics",
           dependencies=["terrain.elevation_m", "ocean.sea_level_m"],
           fidelity_levels=["component_shape"], valid_range=[0.0, 1.0], status=I,
           description="High where exposed land is long, narrow, and component-scale elongated."),
        _f("tectonics.coastline_complexity", SF, "surface_cells", "1", "diagnostics",
           dependencies=["terrain.elevation_m", "ocean.sea_level_m"],
           fidelity_levels=["component_shape"], valid_range=[0.0, 1.0], status=I,
           description="Normalized per-component exposed-land perimeter complexity."),
        _f("tectonics.narrow_neck_index", SF, "surface_cells", "1", "diagnostics",
           dependencies=["terrain.elevation_m", "ocean.sea_level_m"],
           fidelity_levels=["graph_articulation"], valid_range=[0.0, 1.0], status=I,
           description="Articulation-cell proxy for one-cell land bridges and narrow necks."),

        # ---------------- impacts ----------------
        _f("impacts.flux", GS, "global", "Myr^-1", "impacts",
           fidelity_levels=["scaling_law"], status=I,
           description="Expected impactor count per Myr (time-decaying bombardment)."),
        _f("impacts.crater_field", SF, "surface_cells", "1", "impacts",
           dependencies=["impacts.flux"], fidelity_levels=["scaling_law"], status=I),

        # ---------------- terrain, sediment, hydrology ----------------
        _f("terrain.bedrock_m", SF, "surface_cells", "m", "terrain",
           dependencies=["crust.thickness_m", "crust.type"],
           conservation_constraints=["mass"], fidelity_levels=["isostasy"],
           valid_range=[-12000.0, 12000.0], status=I,
           description="Isostatic bedrock surface before sediment."),
        _f("terrain.elevation_m", SF, "surface_cells", "m", "terrain",
           dependencies=["terrain.bedrock_m", "sediment.thickness_m"],
           fidelity_levels=["isostasy_erosion"], valid_range=[-12000.0, 12000.0],
           status=I, validation="hypsometry bimodal for mobile-lid worlds",
           description="Solid surface elevation relative to geoid."),
        _f("sediment.thickness_m", SF, "surface_cells", "m", "terrain",
           dependencies=["terrain.bedrock_m", "hydrology.flow_accumulation"],
           conservation_constraints=["mass"], fidelity_levels=["diffusion_streampower"],
           valid_range=[0.0, 20000.0], status=I),
        _f("terrain.lithology", SF, "surface_cells", "1", "terrain",
           dependencies=["crust.type", "tectonics.volcanoes"],
           fidelity_levels=["categorical"], status=I,
           description="Igneous/sedimentary/metamorphic class (host rock for resources)."),
        _f("terrain.province", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.elevation_m", "crust.domain"],
           fidelity_levels=["regionalized"], status=I,
           description="Terrain province: ocean, craton, platform, margin, terrane, suture, LIP, highland."),
        _f("terrain.continental_detail", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.elevation_m", "terrain.province", "crust.domain",
                         "crust.stability", "tectonics.orogeny_age_myr"],
           fidelity_levels=["regionalized"], status=I,
           description="P13 continental detail province: ocean, shield, platform, basin, rift basin, orogen, plateau, arc/microcontinent."),
        _f("terrain.internal_geographic_block_region_code", SF, "surface_cells", "1",
           "terrain",
           dependencies=["tectonics.internal_geographic_block_code",
                         "crust.type"],
           fidelity_levels=["regionalized_expression"], status=I,
           description="P104D render-scale expression of inherited internal continental blocks; does not feed back into tectonic cargo or elevation."),
        _f("terrain.continental_detail_region_code", SF, "surface_cells", "1",
           "terrain",
           dependencies=["terrain.continental_detail",
                         "terrain.internal_geographic_block_region_code",
                         "terrain.continental_province_code"],
           fidelity_levels=["regionalized_expression"], status=I,
           description="P104E render/compiler-scale continental detail expression derived from region/province objects rather than raw parcel cargo."),
        _f("terrain.inland_geomorphology_region_code", SF, "surface_cells", "1",
           "terrain",
           dependencies=["terrain.elevation_m",
                         "terrain.continental_detail_region_code",
                         "terrain.continental_province_code",
                         "crust.thickness_m", "crust.stability",
                         "tectonics.rift_potential"],
           fidelity_levels=["regionalized_expression"], status=I,
           description="P104F inland physiographic region expression used for bounded province-scale continental-interior elevation response."),
        _f("terrain.continental_province_id", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.continental_detail", "terrain.continental_landforms",
                         "terrain.arc_plume_landforms", "tectonics.continent_id"],
           fidelity_levels=["production_province_graph"], status=I,
           description="Persistent cell-level continental physiographic province id compiled from process-backed terrain and tectonic objects."),
        _f("terrain.continental_province_code", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.continental_province_id"],
           fidelity_levels=["production_province_graph"], status=I,
           description="Reference province class code: shield, platform, basin, foreland, orogen, rift, passive margin, or volcanic/LIP plateau."),
        _f("tectonics.continental_province_id", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.continental_province_id"],
           fidelity_levels=["production_province_graph"], status=I,
           description="Alias of terrain.continental_province_id for tectonics and archive diagnostics."),
        _f("tectonics.continental_province_code", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.continental_province_code"],
           fidelity_levels=["production_province_graph"], status=I,
           description="Alias of terrain.continental_province_code for tectonics and archive diagnostics."),
        _f("tectonics.province_parent_process", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.continental_province_code",
                         "tectonics.boundary_objects", "tectonics.lips"],
           fidelity_levels=["production_province_graph"], status=I,
           description="Parent process code for each continental province cell."),
        _f("tectonics.continental_provinces", OBJ, "surface_cells", "1", "terrain",
           dependencies=["terrain.continental_province_id",
                         "terrain.continental_province_code",
                         "tectonics.province_parent_process"],
           fidelity_levels=["production_province_graph"], status=I,
           description="Persistent continental province objects with class, parent process, parent tectonic links, and adjacency."),
        _f("terrain.passive_margin_lowland", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.elevation_m", "crust.domain",
                         "tectonics.boundary_objects", "sediment.thickness_m"],
           fidelity_levels=["process_template"], status=I,
           description="P74 passive-margin lowland template mask used for coastal-plain terrain response and landform objects."),
        _f("terrain.continental_landforms", OBJ, "surface_cells", "1", "terrain",
           dependencies=["terrain.continental_detail", "terrain.elevation_m",
                         "sediment.thickness_m", "crust.domain",
                         "tectonics.orogeny_age_myr"],
           fidelity_levels=["object_derived"], status=I,
           description="Object-derived continental landforms: shield, platform, interior basin, passive-margin lowland, rift basin, orogen, plateau, foreland basin, arc/microcontinent."),
        _f("terrain.mountain_ranges", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.continental_province_id",
                         "terrain.continental_landforms",
                         "terrain.elevation_m"],
           fidelity_levels=["production_landform_inventory"], status=I,
           description="Production mountain range id field compiled from parented orogen, old-orogen, plateau, and arc landform objects."),
        _f("terrain.mountain_inventory", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.mountain_ranges"],
           fidelity_levels=["production_landform_inventory"], status=I,
           description="Mountain inventory class code for active orogens, old subdued orogens, plateaus, and arc chains."),
        _f("terrain.mountain_hierarchy_level", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.mountain_inventory"],
           fidelity_levels=["production_landform_inventory"], status=I,
           description="Mountain inventory hierarchy level; plateau cores are subordinate to broader range systems."),
        _f("terrain.orogenic_parent_hierarchy", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.continental_landforms",
                         "terrain.mountain_inventory",
                         "tectonics.boundary_objects"],
           fidelity_levels=["production_landform_inventory"], status=I,
           description="P111.6.8 guarded parent-line orogenic hierarchy code: 1 foreland slope, 2 branch range, 3 main crest."),
        _f("terrain.orogenic_hierarchy_spine", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.orogenic_parent_hierarchy"],
           fidelity_levels=["production_landform_inventory"], status=I,
           description="P111.6.14 thin-line QA field derived from the orogenic hierarchy: 2 branch spine, 3 main crest spine."),
        _f("terrain.orogenic_shoulder_halo", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.orogenic_parent_hierarchy",
                         "terrain.orogenic_hierarchy_spine"],
           fidelity_levels=["production_landform_inventory"], status=I,
           description="P111.6.15 shoulder/foothill halo around supported orogenic spines; 1 marks low-to-mid elevation belt fringe."),
        _f("terrain.orogenic_highland_apron", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.orogenic_parent_hierarchy",
                         "terrain.orogenic_hierarchy_spine",
                         "terrain.orogenic_shoulder_halo"],
           fidelity_levels=["production_landform_inventory"], status=I,
           description="P111.6.16 high-latitude highland apron around broad orogens; 1 marks elevated apron cells split from peak hierarchy."),
        _f("tectonics.mountain_belt_id", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.mountain_ranges"],
           fidelity_levels=["production_landform_inventory"], status=I,
           description="Alias of terrain.mountain_ranges for tectonic provenance and archive diagnostics."),
        _f("tectonics.mountain_parent_process_id", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.mountain_inventory",
                         "tectonics.province_parent_process"],
           fidelity_levels=["production_landform_inventory"], status=I,
           description="Parent-process code for production mountain inventory cells."),
        _f("terrain.plateau_inventory", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.continental_province_code",
                         "terrain.mountain_inventory", "crust.domain"],
           fidelity_levels=["production_landform_lifecycle"], status=I,
           description="Plateau inventory class code: collision plateau or volcanic/LIP plateau."),
        _f("terrain.plateau_age_myr", SF, "surface_cells", "Myr", "terrain",
           dependencies=["terrain.plateau_inventory",
                         "tectonics.orogeny_age_myr", "crust.age_myr"],
           fidelity_levels=["production_landform_lifecycle"], status=I,
           description="Approximate plateau lifecycle age for collision and volcanic/LIP plateau cells."),
        _f("terrain.plateau_decay_stage", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.plateau_age_myr",
                         "terrain.plateau_inventory"],
           fidelity_levels=["production_landform_lifecycle"], status=I,
           description="Plateau lifecycle stage code from incipient/emplacement through eroded/dissected state."),
        _f("terrain.plateau_parent_process_id", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.plateau_inventory",
                         "tectonics.province_parent_process"],
           fidelity_levels=["production_landform_lifecycle"], status=I,
           description="Parent process code for plateau inventory cells."),
        _f("tectonics.plateau_lineage_id", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.plateau_inventory"],
           fidelity_levels=["production_landform_lifecycle"], status=I,
           description="Plateau lineage id field used for archive continuity and lifecycle diagnostics."),
        _f("terrain.rift_shoulders", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.rift_margin_sequence_id",
                         "tectonics.rift_margin_lineage_id",
                         "terrain.elevation_m"],
           fidelity_levels=["production_bathymetry_margin_sequence"], status=I,
           description="Production rift-shoulder object id field for rift-to-passive-margin lifecycle diagnostics."),
        _f("terrain.escarpments", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.rift_margin_sequence_id",
                         "tectonics.rift_margin_lineage_id",
                         "terrain.elevation_m"],
           fidelity_levels=["production_bathymetry_margin_sequence"], status=I,
           description="Production passive-margin escarpment object id field tied to rift-margin sequence lineage."),
        _f("terrain.rift_margin_sequence_id", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.rift_margin_stage", "ocean.depth_province",
                         "terrain.passive_margin_lowland"],
           fidelity_levels=["production_bathymetry_margin_sequence"], status=I,
           description="Production rift-to-passive-margin sequence id spanning shoulder/basin/lowland and shelf-slope-rise-abyss zones."),
        _f("terrain.rift_margin_stage", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.elevation_m", "terrain.continental_detail",
                         "ocean.depth_province", "ocean.margin_type"],
           fidelity_levels=["production_bathymetry_margin_sequence"], status=I,
           description="Rift-margin lifecycle stage code: shoulder, rift basin, escarpment, passive lowland, shelf, slope, rise, abyss."),
        _f("tectonics.rift_margin_lineage_id", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.rift_margin_sequence_id"],
           fidelity_levels=["production_bathymetry_margin_sequence"], status=I,
           description="Lineage id for generated rift-to-passive-margin sequence cells."),
        _f("terrain.rift_margin_sequences", OBJ, "surface_cells", "1", "terrain",
           dependencies=["terrain.rift_margin_sequence_id",
                         "terrain.rift_margin_stage",
                         "tectonics.rift_margin_lineage_id"],
           fidelity_levels=["production_bathymetry_margin_sequence"], status=I,
           description="Production objects for rift-to-passive-margin sequence components and their stage inventory."),
        _f("terrain.margin_landforms", OBJ, "surface_cells", "1", "terrain",
           dependencies=["ocean.margin_type", "ocean.depth_province",
                         "ocean.shelf_width", "terrain.elevation_m",
                         "sediment.thickness_m", "hydrology.rivers",
                         "tectonics.boundary_objects"],
           fidelity_levels=["object_derived"], status=I,
           description="Object-derived margin landforms: passive sediment wedge, trench, forearc/accretionary prism, volcanic arc, delta/fan."),
        _f("terrain.ocean_fabric", OBJ, "surface_cells", "1", "terrain",
           dependencies=["ocean.depth_province", "terrain.elevation_m",
                         "sediment.thickness_m", "crust.age_myr",
                         "tectonics.boundary_objects",
                         "tectonics.spreading_centers"],
           fidelity_levels=["object_derived"], status=I,
           description="Object-derived ocean-basin fabric: spreading centers, transform faults, fracture zones, abyssal plains, age isochron bands."),
        _f("terrain.arc_plume_landforms", OBJ, "surface_cells", "1", "terrain",
           dependencies=["terrain.elevation_m", "crust.origin", "crust.domain",
                         "crust.thickness_m", "tectonics.volcanism_age_myr",
                         "tectonics.terranes", "tectonics.plumes",
                         "tectonics.lips", "tectonics.boundary_objects"],
           fidelity_levels=["object_derived"], status=I,
           description="Object-derived arc/plume landforms: island arcs, accreted terranes, back-arc basins, hotspot tracks, and large igneous provinces."),
        _f("terrain.cryosphere_landforms", OBJ, "surface_cells", "1", "terrain",
           dependencies=["terrain.elevation_m", "sediment.thickness_m",
                         "cryosphere.ice_sheet"],
           fidelity_levels=["object_derived"], status=I,
           description="Object-derived cryosphere landforms: ice-sheet loading, glacial erosion, and postglacial rebound."),
        _f("hydrology.flow_accumulation", SF, "surface_cells", "m^2", "terrain",
           dependencies=["terrain.elevation_m", "climate.runoff"],
           conservation_constraints=["water"], fidelity_levels=["d8_priority_flood"],
           status=I),
        _f("hydrology.rivers", NET, "surface_cells", "1", "terrain",
           dependencies=["hydrology.flow_accumulation"],
           fidelity_levels=["steepest_descent"], status=I,
           validation="no cyclic flow; all flow reaches ocean or endorheic sink"),
        _f("ocean.sea_level_m", GS, "global", "m", "terrain",
           dependencies=["terrain.bedrock_m"],
           conservation_constraints=["water"], fidelity_levels=["volume_balance"],
           status=I, description="Global sea level from ocean water volume vs hypsometry."),
        _f("terrain.basins", OBJ, "surface_cells", "1", "terrain",
           dependencies=["terrain.elevation_m"], fidelity_levels=["rule_based"], status=I),

        # ---------------- atmosphere & ocean (climate) ----------------
        _f("climate.surface_temperature", SF, "surface_cells", "K", "climate",
           dependencies=["stellar.surface_flux", "atmosphere.co2", "terrain.elevation_m",
                         "ocean.mask", "cryosphere.sea_ice"],
           time_support="monthly_climatology", fidelity_levels=["ebm", "reduced", "gcm"],
           conservation_constraints=["energy"], uncertainty="ensemble",
           valid_range=[120.0, 360.0], status=I,
           validation="global energy budget closes; no land-crossing currents"),
        _f("climate.seasonal_temperature", SF, "season_surface_cells", "K", "climate",
           dependencies=["climate.surface_temperature", "stellar.surface_flux",
                         "orbit.obliquity", "orbit.eccentricity", "ocean.mask"],
           time_support="seasonal_climatology", fidelity_levels=["seasonal_ebm_proxy"],
           conservation_constraints=["energy"], uncertainty="ensemble",
           valid_range=[120.0, 360.0], status=I,
           validation="four-season mean equals annual surface temperature"),
        _f("climate.temperature_seasonality", SF, "surface_cells", "K", "climate",
           dependencies=["climate.seasonal_temperature"],
           time_support="annual_diagnostic", fidelity_levels=["seasonal_ebm_proxy"],
           valid_range=[0.0, 120.0], status=I,
           description="Four-season max-min surface temperature amplitude."),
        _f("climate.seasonal_sst", SF, "season_surface_cells", "K", "climate",
           dependencies=["climate.seasonal_temperature", "ocean.sst_anomaly",
                         "ocean.upwelling", "ocean.mask"],
           time_support="seasonal_climatology",
           fidelity_levels=["weak_ocean_atmosphere_coupling"],
           valid_range=[120.0, 360.0], status=I,
           description="Four-season sea-surface temperature after current/upwelling feedback."),
        _f("climate.seasonal_insolation_anomaly", SF, "season_surface_cells",
           "W m^-2", "climate",
           dependencies=["stellar.surface_flux", "orbit.obliquity",
                         "orbit.eccentricity"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["M1_energy_boundary_diagnostic"],
           status=I,
           description="M1 diagnostic: seasonal top-of-atmosphere insolation anomaly relative to each cell's four-season mean."),
        _f("climate.surface_heat_capacity_class", SF, "surface_cells", "1",
           "climate",
           dependencies=["ocean.mask", "climate.continentality"],
           time_support="static_diagnostic",
           fidelity_levels=["M1_energy_boundary_diagnostic"],
           valid_range=[0.0, 1.0], status=I,
           description="M1 diagnostic: reduced thermal-inertia class; ocean and maritime cells respond more slowly than continental interiors."),
        _f("climate.land_thermal_anomaly", SF, "season_surface_cells", "K",
           "climate",
           dependencies=["climate.seasonal_temperature", "ocean.mask"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["M1_energy_boundary_diagnostic"],
           valid_range=[-80.0, 80.0], status=I,
           description="M1 diagnostic: land-only seasonal temperature anomaly relative to each cell's annual mean; ocean is zero."),
        _f("climate.ocean_mixed_layer_thermal_anomaly", SF,
           "season_surface_cells", "K", "climate",
           dependencies=["climate.seasonal_sst", "ocean.mask"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["M1_energy_boundary_diagnostic"],
           valid_range=[-40.0, 40.0], status=I,
           description="M1 diagnostic: ocean-only seasonal SST anomaly relative to each cell's annual mean; land is zero."),
        _f("climate.elevation_lapse_cooling", SF, "surface_cells", "K",
           "climate",
           dependencies=["terrain.elevation_m"],
           time_support="static_diagnostic",
           fidelity_levels=["M1_energy_boundary_diagnostic"],
           valid_range=[0.0, 80.0], status=I,
           description="M1 diagnostic: elevation-driven lapse-rate cooling used to attribute thermal and pressure residuals."),
        _f("climate.snow_ice_albedo_support", SF, "season_surface_cells", "1",
           "climate",
           dependencies=["cryosphere.seasonal_sea_ice", "cryosphere.seasonal_snow"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["M1_energy_boundary_diagnostic"],
           valid_range=[0.0, 1.0], status=I,
           description="M1 diagnostic: combined seasonal sea-ice and land-snow albedo support."),
        _f("climate.sst_gradient_support", SF, "season_surface_cells", "1",
           "climate",
           dependencies=["climate.seasonal_sst", "ocean.mask"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["M1_energy_boundary_diagnostic"],
           valid_range=[0.0, 1.5], status=I,
           description="M1 diagnostic: normalized seasonal SST-front support for later pressure, wind, and storm-track attribution."),
        _f("climate.same_latitude_sst_anomaly", SF, "season_surface_cells",
           "K", "climate",
           dependencies=["climate.seasonal_sst", "ocean.mask"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["M1_energy_boundary_diagnostic"],
           valid_range=[-40.0, 40.0], status=I,
           description="M1 diagnostic: ocean SST residual after removing same-latitude band mean, used to detect over-zonal SST forcing."),
        _f("climate.land_sea_thermal_contrast", SF, "season_surface_cells",
           "K", "climate",
           dependencies=["climate.land_thermal_anomaly",
                         "climate.ocean_mixed_layer_thermal_anomaly",
                         "climate.coast_distance"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["M1_energy_boundary_diagnostic"],
           valid_range=[-45.0, 45.0], status=I,
           description="M1 diagnostic: locally spread land-minus-ocean seasonal thermal contrast for R2a pressure-source attribution."),
        _f("climate.seasonal_cloud_albedo_proxy", SF, "season_surface_cells", "1",
           "climate",
           dependencies=["atmosphere.moisture_access",
                         "atmosphere.storm_track_intensity",
                         "climate.seasonal_precipitation",
                         "climate.seasonal_temperature"],
           time_support="seasonal_climatology",
           fidelity_levels=["bounded_cloud_albedo_proxy"],
           valid_range=[0.0, 1.0], status=I,
           description="Seasonal cloud/albedo proxy from moisture access, storm tracks, precipitation, ocean exposure, and cold stability."),
        _f("climate.cloud_albedo_proxy", SF, "surface_cells", "1", "climate",
           dependencies=["climate.seasonal_cloud_albedo_proxy"],
           time_support="annual_diagnostic",
           fidelity_levels=["bounded_cloud_albedo_proxy"],
           valid_range=[0.0, 1.0], status=I,
           description="Annual mean cloud/albedo proxy used as a C5 feedback diagnostic."),
        _f("climate.ocean_heat_flux", SF, "ocean_cells", "K", "climate",
           dependencies=["ocean.sst_anomaly", "ocean.upwelling", "ocean.mask"],
           time_support="annual_diagnostic",
           fidelity_levels=["weak_ocean_atmosphere_coupling"],
           valid_range=[-10.0, 10.0], status=I,
           description="Mean-zero ocean heat anomaly used by SST, evaporation, and pressure coupling."),
        _f("climate.coupling_residual", SF, "ocean_cells", "K", "climate",
           dependencies=["climate.ocean_heat_flux", "atmosphere.seasonal_wind",
                         "ocean.sst_anomaly"],
           time_support="annual_diagnostic",
           fidelity_levels=["weak_ocean_atmosphere_coupling"],
           valid_range=[0.0, 10.0], status=I,
           description="Residual SST-anomaly change after reduced ocean-atmosphere coupling iterations."),
        _f("climate.continentality", SF, "surface_cells", "1", "climate",
           dependencies=["ocean.mask"],
           time_support="static_geography", fidelity_levels=["graph_distance_proxy"],
           valid_range=[0.0, 1.0], status=I,
           description="Land-ocean thermal inertia proxy used by seasonal climate."),
        _f("climate.continent_id", SF, "surface_cells", "1", "climate",
           dependencies=["ocean.mask"], time_support="static_geography",
           fidelity_levels=["graph_components"], status=I,
           description="Connected exposed-land component id; ocean cells are -1."),
        _f("climate.continent_interiority", SF, "surface_cells", "1", "climate",
           dependencies=["climate.continent_id", "ocean.mask"],
           time_support="static_geography", fidelity_levels=["graph_distance_proxy"],
           valid_range=[0.0, 1.0], status=I,
           description="Distance/insulation from ocean, scaled by continent size."),
        _f("climate.coast_orientation", VF, "surface_cells", "1", "climate",
           dependencies=["ocean.mask"], time_support="static_geography",
           fidelity_levels=["coast_graph"], status=I,
           description="Tangent oceanward vector on coastal land; zero elsewhere."),
        _f("climate.coast_distance", SF, "surface_cells", "1", "climate",
           dependencies=["ocean.mask"], time_support="static_geography",
           fidelity_levels=["graph_distance_proxy"], valid_range=[0.0, 1.0],
           status=I, description="Normalized graph distance from nearest coastline."),
        _f("climate.coast_strength", SF, "surface_cells", "1", "climate",
           dependencies=["ocean.mask"], time_support="static_geography",
           fidelity_levels=["coast_graph"], valid_range=[0.0, 1.0], status=I,
           description="Fractional local coastline adjacency on coastal land."),
        _f("climate.coast_facing_east", SF, "surface_cells", "1", "climate",
           dependencies=["climate.coast_orientation"], time_support="static_geography",
           fidelity_levels=["diagnostic"], valid_range=[-1.0, 1.0], status=I,
           description="East-west component of oceanward coast orientation."),
        _f("climate.precipitation", SF, "surface_cells", "mm yr^-1", "climate",
           dependencies=["climate.surface_temperature", "atmosphere.wind",
                         "terrain.elevation_m", "ocean.mask"],
           time_support="monthly_climatology", conservation_constraints=["water"],
           fidelity_levels=["moisture_advection"], valid_range=[0.0, 12000.0], status=I,
           validation="orographic windward wet / leeward rain-shadow dry"),
        _f("climate.seasonal_precipitation", SF, "season_surface_cells",
           "mm yr^-1", "climate",
           dependencies=["climate.seasonal_temperature", "atmosphere.seasonal_wind",
                         "atmosphere.moisture_access", "atmosphere.monsoon_potential",
                         "terrain.barrier_index", "ocean.upwelling"],
           time_support="seasonal_climatology", conservation_constraints=["water"],
           fidelity_levels=["seasonal_moisture_proxy"], valid_range=[0.0, 12000.0],
           status=I,
           description="Four-season precipitation intensity; mean equals annual precipitation."),
        _f("climate.monsoon_rainfall_corridor", SF, "season_surface_cells", "1",
           "climate",
           dependencies=["atmosphere.monsoon_potential",
                         "atmosphere.moisture_access",
                         "atmosphere.seasonal_pressure_proxy",
                         "climate.seasonal_sst",
                         "climate.coast_orientation",
                         "terrain.barrier_index"],
           time_support="seasonal_climatology",
           fidelity_levels=["regional_hydroclimate_proxy"],
           valid_range=[0.0, 1.5], status=I,
           description="Regional monsoon-rain corridor derived from heat lows, onshore flow, warm source oceans, moisture access, and terrain passability."),
        _f("climate.storm_track_rainfall_corridor", SF, "season_surface_cells",
           "1", "climate",
           dependencies=["atmosphere.storm_track_intensity",
                         "atmosphere.moisture_access",
                         "atmosphere.seasonal_wind",
                         "terrain.barrier_index"],
           time_support="seasonal_climatology",
           fidelity_levels=["regional_hydroclimate_proxy"],
           valid_range=[0.0, 1.5], status=I,
           description="Regional storm-track rainfall corridor before seasonal precipitation aggregation."),
        _f("climate.rain_shadow_index", SF, "season_surface_cells", "1",
           "climate",
           dependencies=["atmosphere.seasonal_wind", "terrain.barrier_index",
                         "terrain.wind_gap_index",
                         "atmosphere.monsoon_potential"],
           time_support="seasonal_climatology",
           fidelity_levels=["regional_hydroclimate_proxy"],
           valid_range=[0.0, 1.5], status=I,
           description="Regional leeward drying corridor from terrain barriers and seasonal winds."),
        _f("climate.regional_precipitation_response", SF, "season_surface_cells",
           "1", "climate",
           dependencies=["climate.monsoon_rainfall_corridor",
                         "climate.storm_track_rainfall_corridor",
                         "climate.rain_shadow_index",
                         "climate.seasonal_precipitation"],
           time_support="seasonal_climatology",
           fidelity_levels=["regional_hydroclimate_proxy"],
           valid_range=[0.4, 1.6], status=I,
           description="Conservative seasonal precipitation shaping response from regional wet/dry corridors."),
        _f("atmosphere.moisture_flow_source", SF, "season_surface_cells", "1",
           "climate",
           dependencies=["ocean.mask", "atmosphere.source_ocean_warmth",
                         "ocean.current_heat_transport", "ocean.upwelling"],
           time_support="seasonal_climatology",
           fidelity_levels=["source_to_sink_proxy"],
           valid_range=[0.0, 1.5], status=I,
           description="Seasonal oceanic moisture source strength used by C4e flow-network extraction."),
        _f("atmosphere.moisture_flow_pathway", SF, "season_surface_cells", "1",
           "climate",
           dependencies=["atmosphere.moisture_flow_source",
                         "atmosphere.seasonal_wind",
                         "atmosphere.moisture_access",
                         "climate.monsoon_rainfall_corridor",
                         "climate.storm_track_rainfall_corridor",
                         "climate.rain_shadow_index",
                         "terrain.barrier_index", "terrain.wind_gap_index"],
           time_support="seasonal_climatology",
           fidelity_levels=["source_to_sink_proxy"],
           valid_range=[0.0, 1.5], status=I,
           description="Seasonal landward moisture pathway strength advected from ocean sources through passable terrain."),
        _f("atmosphere.moisture_source_basin_id", SF, "season_surface_cells",
           "1", "climate",
           dependencies=["atmosphere.moisture_flow_source",
                         "atmosphere.moisture_flow_pathway",
                         "atmosphere.seasonal_wind",
                         "ocean.basin_id"],
           time_support="seasonal_climatology",
           fidelity_levels=["source_to_sink_proxy"],
           valid_range=[-1.0, 10000.0], status=I,
           description="C4i dominant ocean-basin id supplying each seasonal moisture-flow pathway cell; -1 marks unattributed cells."),
        _f("climate.moisture_flow_network_id", SF, "season_surface_cells", "1",
           "climate",
           dependencies=["atmosphere.moisture_flow_pathway"],
           time_support="seasonal_climatology",
           fidelity_levels=["component_objects"],
           valid_range=[-1.0, 10000.0], status=I,
           description="Seasonal connected moisture-flow network id; -1 marks inactive cells."),
        _f("climate.moisture_flow_networks", OBJ, "season_surface_cells", "1",
           "climate",
           dependencies=["atmosphere.moisture_flow_pathway",
                         "climate.moisture_flow_network_id",
                         "climate.seasonal_precipitation"],
           time_support="seasonal_climatology",
           fidelity_levels=["component_objects"], status=I,
           description="Explicit C4e seasonal moisture-flow network objects linking source moisture pathways to monsoon, storm-track, and mixed wet corridors."),
        _f("climate.moisture_flow_precipitation_response", SF,
           "season_surface_cells", "1", "climate",
           dependencies=["atmosphere.moisture_flow_pathway",
                         "climate.moisture_flow_network_id",
                         "climate.seasonal_precipitation"],
           time_support="seasonal_climatology",
           conservation_constraints=["water"],
           fidelity_levels=["source_to_sink_proxy"],
           valid_range=[0.4, 2.0], status=I,
           description="C4f conservative seasonal precipitation redistribution response from routed moisture-flow networks; seasonal land mean is preserved."),
        _f("climate.moisture_budget_region_id", SF,
           "season_surface_cells", "1", "climate",
           dependencies=["climate.continent_id",
                         "atmosphere.moisture_flow_pathway",
                         "atmosphere.moisture_source_basin_id",
                         "climate.moisture_flow_network_id",
                         "climate.seasonal_precipitation"],
           time_support="seasonal_climatology",
           conservation_constraints=["water"],
           fidelity_levels=["continent_network_sector_budget_proxy"],
           valid_range=[-1.0, 10000.0], status=I,
           description="C4g/C4h local seasonal land precipitation budget region id: continent-scale budgets plus safe large moisture-network sector splits used to preserve response means locally instead of only globally."),
        _f("climate.precipitation_response_region_id", SF,
           "season_surface_cells", "1", "climate",
           dependencies=["climate.moisture_flow_precipitation_response",
                         "climate.moisture_budget_region_id",
                         "atmosphere.moisture_source_basin_id",
                         "climate.moisture_flow_network_id",
                         "climate.seasonal_precipitation"],
           time_support="seasonal_climatology",
           fidelity_levels=["precipitation_response_region_objects"],
           valid_range=[-1.0, 10000.0], status=I,
           description="C4j seasonal wet/dry precipitation-response object id; -1 marks cells outside archived final response regions."),
        _f("climate.receiver_catchment_id", SF,
           "season_surface_cells", "1", "climate",
           dependencies=["climate.moisture_budget_region_id",
                         "climate.precipitation_response_region_id",
                         "atmosphere.moisture_source_basin_id",
                         "climate.moisture_flow_network_id",
                         "climate.seasonal_precipitation"],
           time_support="seasonal_climatology",
           fidelity_levels=["receiver_catchment_objects"],
           valid_range=[-1.0, 10000.0], status=I,
           description="C4k seasonal receiver-side catchment id: stable contiguous land accounting domains grouped by local budget region and materially dominant source basin."),
        _f("climate.source_basin_supply_index", SF,
           "season_surface_cells", "1", "climate",
           dependencies=["atmosphere.moisture_flow_source",
                         "atmosphere.moisture_flow_pathway",
                         "atmosphere.moisture_source_basin_id",
                         "climate.receiver_catchment_id",
                         "climate.seasonal_precipitation"],
           time_support="seasonal_climatology",
           fidelity_levels=["source_receiver_accounting"],
           valid_range=[0.0, 1.5], status=I,
           description="C5e7 bounded seasonal source-ocean-basin supply support index over ocean source cells and attributed receiving land cells."),
        _f("climate.receiver_catchment_supply_balance", SF,
           "season_surface_cells", "1", "climate",
           dependencies=["climate.source_basin_supply_index",
                         "climate.receiver_catchment_id",
                         "climate.seasonal_precipitation",
                         "climate.moisture_flow_precipitation_response"],
           time_support="seasonal_climatology",
           fidelity_levels=["source_receiver_accounting"],
           valid_range=[0.0, 1.0], status=I,
           description="C5e7 dimensionless receiver-catchment precipitation-versus-source-supply consistency diagnostic; not a strict water-conservation solve."),
        _f("climate.receiver_supply_precipitation_feedback", SF,
           "season_surface_cells", "1", "climate",
           dependencies=["climate.source_basin_supply_index",
                         "climate.receiver_catchment_supply_balance",
                         "climate.moisture_budget_region_id",
                         "climate.seasonal_precipitation"],
           time_support="seasonal_climatology",
           conservation_constraints=["water"],
           fidelity_levels=["source_receiver_feedback"],
           valid_range=[0.8, 1.2], status=I,
           description="C5e8 bounded land-only precipitation redistribution feedback from source-basin supply and receiver-catchment balance; seasonal local moisture-budget means are preserved."),
        _f("climate.precipitation_seasonality", SF, "surface_cells", "1",
           "climate",
           dependencies=["climate.seasonal_precipitation"],
           time_support="annual_diagnostic", fidelity_levels=["diagnostic"],
           valid_range=[1.0, 4.0], status=I,
           description="Peak seasonal precipitation divided by annual mean."),
        _f("climate.monsoon_index", SF, "surface_cells", "1", "climate",
           dependencies=["climate.seasonal_precipitation",
                         "atmosphere.monsoon_potential"],
           time_support="annual_diagnostic", fidelity_levels=["diagnostic"],
           valid_range=[-3.0, 3.0], status=I,
           description="Signed summer-wet / winter-dry precipitation contrast."),
        _f("climate.dry_season_length", SF, "surface_cells", "season_count",
           "climate",
           dependencies=["climate.seasonal_precipitation"],
           time_support="annual_diagnostic", fidelity_levels=["diagnostic"],
           valid_range=[0.0, 4.0], status=I,
           description="Number of dry seasons in the four-season climatology."),
        _f("climate.wet_season_peak", SF, "surface_cells", "season_index",
           "climate",
           dependencies=["climate.seasonal_precipitation"],
           time_support="annual_diagnostic", fidelity_levels=["diagnostic"],
           valid_range=[0.0, 3.0], status=I,
           description="Index of the wettest season: 0 DJF, 1 MAM, 2 JJA, 3 SON."),
        _f("climate.moisture_convergence", SF, "surface_cells", "1",
           "climate",
           dependencies=["atmosphere.moisture_access", "atmosphere.seasonal_wind"],
           time_support="annual_diagnostic", fidelity_levels=["diagnostic"],
           valid_range=[0.0, 3.0], status=I,
           description="Annual diagnostic for seasonal moisture convergence strength."),
        _f("climate.orographic_precipitation", SF, "surface_cells", "mm yr^-1",
           "climate",
           dependencies=["climate.seasonal_precipitation", "terrain.barrier_index"],
           time_support="annual_diagnostic", fidelity_levels=["diagnostic"],
           valid_range=[0.0, 4000.0], status=I,
           description="Orographic precipitation contribution after climate-scale smoothing."),
        _f("climate.evaporation", SF, "surface_cells", "mm yr^-1", "climate",
           dependencies=["climate.surface_temperature", "ocean.mask"],
           conservation_constraints=["water"], fidelity_levels=["bulk"], status=I),
        _f("climate.runoff", SF, "surface_cells", "mm yr^-1", "climate",
           dependencies=["climate.precipitation", "climate.evaporation"],
           conservation_constraints=["water"], fidelity_levels=["balance"], status=I),
        _f("atmosphere.wind", VF, "surface_cells", "m s^-1", "climate",
           dependencies=["climate.surface_temperature", "orbit.obliquity"],
           fidelity_levels=["banded", "gcm"], status=I,
           description="Idealised Hadley/Ferrel/Polar banded winds (+ tidal-lock cell)."),
        _f("atmosphere.seasonal_wind", VF, "season_surface_cells", "m s^-1", "climate",
           dependencies=["climate.seasonal_temperature", "orbit.obliquity",
                         "orbit.eccentricity"],
           time_support="seasonal_climatology", fidelity_levels=["migrating_bands"],
           status=I,
           validation="seasonal wind vectors tangent to the sphere"),
        _f("atmosphere.background_seasonal_wind", VF, "season_surface_cells",
           "m s^-1", "climate",
           dependencies=["climate.seasonal_temperature", "orbit.obliquity",
                         "orbit.eccentricity"],
           time_support="seasonal_climatology", fidelity_levels=["migrating_bands"],
           status=I,
           description="Astronomical/zonal background wind before geographic anomalies."),
        _f("atmosphere.land_sea_pressure_proxy", SF, "season_surface_cells", "1",
           "climate",
           dependencies=["climate.seasonal_temperature", "climate.continentality",
                         "ocean.mask"],
           time_support="seasonal_climatology", fidelity_levels=["thermal_proxy"],
           valid_range=[-2.0, 2.0], status=I,
           description="Seasonal thermal low/high proxy from land-ocean contrast."),
        _f("atmosphere.seasonal_pressure_proxy", SF, "season_surface_cells",
           "1", "climate",
           dependencies=["atmosphere.land_sea_pressure_proxy",
                         "atmosphere.source_ocean_warmth", "ocean.upwelling"],
           time_support="seasonal_climatology", fidelity_levels=["thermal_moisture_proxy"],
           valid_range=[-2.5, 2.5], status=I,
           description="Seasonal pressure proxy after source-ocean and current effects."),
        _f("atmosphere.pressure_center_support", SF, "season_surface_cells",
           "1", "climate",
           dependencies=["atmosphere.land_sea_pressure_proxy",
                         "climate.continent_id", "ocean.basin_id"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["pressure_center_objects"], valid_range=[0.0, 1.5],
           status=I,
           description="Diagnostic support for seasonal pressure high/low centers."),
        _f("atmosphere.pressure_center_id", SF, "season_surface_cells",
           "1", "climate",
           dependencies=["atmosphere.pressure_center_support"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["component_objects"], status=I,
           description="Seasonal pressure-center object id per cell; zero outside centers."),
        _f("atmosphere.stationary_wave_pressure_support", SF,
           "season_surface_cells", "1", "climate",
           dependencies=["atmosphere.land_sea_pressure_proxy",
                         "terrain.barrier_index", "climate.coast_strength"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["stationary_wave_proxy"], valid_range=[0.0, 1.5],
           status=I,
           description="Pressure-center support weighted by coast and orographic anchors."),
        _f("atmosphere.pressure_genesis_source", SF, "season_surface_cells",
           "1", "climate",
           dependencies=["ocean.basin_id", "climate.seasonal_sst",
                         "terrain.barrier_index",
                         "atmosphere.land_sea_pressure_proxy"],
           time_support="seasonal_climatology",
           fidelity_levels=["basin_front_pressure_source"],
           valid_range=[-1.5, 1.5], status=I,
           description="Signed M2 causal pressure-source increment before R2b wind translation."),
        _f("atmosphere.pressure_genesis_wave_transfer", SF,
           "season_surface_cells", "1", "climate",
           dependencies=["atmosphere.pressure_genesis_source",
                         "atmosphere.land_sea_pressure_proxy",
                         "atmosphere.land_pressure_source_support",
                         "atmosphere.terrain_pressure_wave_source_support"],
           time_support="seasonal_climatology",
           fidelity_levels=["basin_front_pressure_source"],
           valid_range=[-1.0, 1.0], status=I,
           description="Bounded M2 transfer that expresses causal source objects in final pressure geometry."),
        _f("atmosphere.ocean_pressure_low_source_support", SF,
           "season_surface_cells", "1", "climate",
           dependencies=["ocean.basin_id", "climate.seasonal_sst"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["basin_front_pressure_source"],
           valid_range=[0.0, 1.5], status=I,
           description="Causal support for basin/front-anchored ocean low-pressure sources."),
        _f("atmosphere.ocean_pressure_high_source_support", SF,
           "season_surface_cells", "1", "climate",
           dependencies=["ocean.basin_id", "climate.seasonal_sst"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["basin_front_pressure_source"],
           valid_range=[0.0, 1.5], status=I,
           description="Causal support for weak basin subtropical high-pressure sources."),
        _f("atmosphere.land_pressure_source_support", SF,
           "season_surface_cells", "1", "climate",
           dependencies=["climate.seasonal_temperature",
                         "climate.continent_interiority"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["thermal_pressure_source"],
           valid_range=[0.0, 1.5], status=I,
           description="Causal support for continent thermal pressure-source refinements."),
        _f("atmosphere.terrain_pressure_wave_source_support", SF,
           "season_surface_cells", "1", "climate",
           dependencies=["terrain.barrier_index",
                         "atmosphere.land_sea_pressure_proxy"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["terrain_stationary_pressure_source"],
           valid_range=[0.0, 1.5], status=I,
           description="Causal support for terrain-anchored stationary pressure-wave refinements."),
        _f("atmosphere.moisture_access", SF, "season_surface_cells", "1",
           "climate",
           dependencies=["atmosphere.seasonal_wind", "atmosphere.source_ocean_warmth",
                         "terrain.barrier_index", "terrain.wind_gap_index"],
           time_support="seasonal_climatology", fidelity_levels=["graph_advection_proxy"],
           valid_range=[0.0, 1.0], status=I,
           description="Seasonal ability of moist source-ocean air to reach cells."),
        _f("atmosphere.monsoon_potential", SF, "season_surface_cells", "1",
           "climate",
           dependencies=["atmosphere.seasonal_pressure_proxy",
                         "atmosphere.moisture_access",
                         "climate.continent_interiority"],
           time_support="seasonal_climatology", fidelity_levels=["diagnostic"],
           valid_range=[-1.0, 1.5], status=I,
           description="Geography-derived seasonal monsoon potential."),
        _f("atmosphere.source_ocean_warmth", SF, "season_surface_cells", "1",
           "climate",
           dependencies=["climate.seasonal_temperature", "ocean.upwelling",
                         "ocean.current_heat_transport"],
           time_support="seasonal_climatology", fidelity_levels=["bulk_sst_proxy"],
           valid_range=[0.0, 1.0], status=I,
           description="Warm, ice-free source-ocean humidity potential."),
        _f("atmosphere.terrain_blocking", SF, "surface_cells", "1",
           "climate",
           dependencies=["terrain.barrier_index", "terrain.wind_gap_index"],
           time_support="static_geography", fidelity_levels=["diagnostic"],
           valid_range=[0.0, 1.0], status=I,
           description="Moisture/wind blocking by climate-scale terrain barriers."),
        _f("atmosphere.thermal_wind_anomaly", VF, "season_surface_cells",
           "m s^-1", "climate",
           dependencies=["atmosphere.land_sea_pressure_proxy", "ocean.mask"],
           time_support="seasonal_climatology", fidelity_levels=["thermal_proxy"],
           status=I,
           description="Geography-driven land-sea thermal wind anomaly."),
        _f("atmosphere.orographic_wind_anomaly", VF, "season_surface_cells",
           "m s^-1", "climate",
           dependencies=["terrain.elevation_m", "atmosphere.thermal_wind_anomaly"],
           time_support="seasonal_climatology", fidelity_levels=["terrain_steering"],
           status=I,
           description="Terrain steering/blocking anomaly applied to seasonal wind."),
        _f("atmosphere.geographic_circulation_index", SF, "surface_cells", "1",
           "climate",
           dependencies=["atmosphere.thermal_wind_anomaly",
                         "atmosphere.orographic_wind_anomaly"],
           time_support="annual_diagnostic", fidelity_levels=["diagnostic"],
           valid_range=[0.0, 2.0], status=I,
           description="Strength of geography-driven circulation anomalies."),
        _f("atmosphere.itcz_latitude", SF, "season", "deg", "climate",
           dependencies=["orbit.obliquity"],
           time_support="seasonal_climatology", fidelity_levels=["analytic"],
           valid_range=[-35.0, 35.0], status=I,
           description="Seasonal ITCZ latitude proxy."),
        _f("atmosphere.itcz_intensity", SF, "season_surface_cells", "1", "climate",
           dependencies=["atmosphere.itcz_latitude"],
           time_support="seasonal_climatology", fidelity_levels=["analytic"],
           valid_range=[0.0, 1.5], status=I,
           description="Seasonal tropical convergence / ITCZ intensity proxy."),
        _f("atmosphere.storm_track_intensity", SF, "season_surface_cells", "1", "climate",
           dependencies=["atmosphere.seasonal_wind", "orbit.obliquity"],
           time_support="seasonal_climatology", fidelity_levels=["analytic"],
           valid_range=[0.0, 2.0], status=I,
           description="Seasonal mid-latitude storm-track intensity proxy."),
        _f("atmosphere.co2", GS, "global", "bar", "biogeochem",
           fidelity_levels=["box"], valid_range=[0.0, 10.0], status=I),
        _f("atmosphere.pressure", GS, "global", "bar", "climate",
           valid_range=[0.0, 100.0], status=I),
        _f("ocean.mask", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.elevation_m", "ocean.sea_level_m"],
           fidelity_levels=["threshold"], status=I),
        _f("ocean.margin_type", SF, "surface_cells", "1", "terrain",
           dependencies=["ocean.mask", "tectonics.boundaries"],
           time_support="static_geography", fidelity_levels=["province_objects"],
           valid_range=[0.0, 5.0], status=I,
           description="Ocean margin class: land, passive, active, ridge, restricted, open."),
        _f("ocean.depth_province", SF, "surface_cells", "1", "terrain",
           dependencies=["terrain.elevation_m", "ocean.sea_level_m", "tectonics.boundaries"],
           time_support="static_geography", fidelity_levels=["bathymetric_provinces"],
           valid_range=[0.0, 7.0], status=I,
           description="Bathymetric province: land, shelf, slope, rise, abyss, ridge, trench, restricted."),
        _f("ocean.gateway_id", SF, "surface_cells", "1", "terrain",
           dependencies=["ocean.mask", "ocean.depth_province", "tectonics.ocean_gateways"],
           time_support="static_geography", fidelity_levels=["graph_components"],
           status=I, description="Ocean gateway component id; non-gateway cells are -1."),
        _f("ocean.gateway_system_id", SF, "surface_cells", "1", "terrain",
           dependencies=["ocean.gateway_id", "ocean.basin_id", "tectonics.ocean_gateways"],
           time_support="static_geography", fidelity_levels=["regional_gateway_systems"],
           status=I, description="Regional ocean gateway/seaway system id; non-system cells are -1."),
        _f("ocean.shelf_width", SF, "surface_cells", "graph steps", "terrain",
           dependencies=["ocean.mask", "terrain.elevation_m"],
           time_support="static_geography", fidelity_levels=["graph_distance"],
           valid_range=[0.0, 1e6], status=I,
           description="Graph-distance band outward from the nearest coast through ocean cells."),
        _f("ocean.currents", VF, "ocean_cells", "m s^-1", "climate",
           dependencies=["atmosphere.wind", "climate.surface_temperature"],
           fidelity_levels=["wind_driven", "thermohaline"], status=I,
           validation="streamlines never cross land"),
        _f("ocean.current_streamfunction", SF, "ocean_cells", "1", "climate",
           dependencies=["atmosphere.seasonal_wind", "ocean.basin_id"],
           time_support="annual_diagnostic", fidelity_levels=["basin_streamfunction"],
           valid_range=[-2.0, 2.0], status=I,
           description="Reduced basin streamfunction used to derive gyre currents."),
        _f("ocean.gyre_id", SF, "ocean_cells", "1", "climate",
           dependencies=["ocean.current_streamfunction", "ocean.basin_id"],
           time_support="annual_diagnostic", fidelity_levels=["basin_streamfunction"],
           status=I, description="Basin gyre component id; weak gyre cells are 0."),
        _f("ocean.boundary_current_type", SF, "ocean_cells", "1", "climate",
           dependencies=["ocean.currents", "ocean.current_streamfunction"],
           time_support="annual_diagnostic", fidelity_levels=["basin_streamfunction"],
           valid_range=[-1.0, 1.0], status=I,
           description="Boundary-current class: warm western boundary +1, cold eastern boundary -1."),
        _f("ocean.strait_exchange", SF, "ocean_cells", "1", "climate",
           dependencies=["ocean.strait_index", "ocean.currents"],
           time_support="annual_diagnostic", fidelity_levels=["basin_streamfunction"],
           valid_range=[0.0, 1.0], status=I,
           description="Relative current exchange through diagnosed straits."),
        _f("ocean.sst_anomaly", SF, "ocean_cells", "K", "climate",
           dependencies=["ocean.current_streamfunction", "ocean.upwelling"],
           time_support="annual_diagnostic", fidelity_levels=["basin_streamfunction"],
           valid_range=[-10.0, 10.0], status=I,
           description="Ocean-only SST anomaly from gyres, boundary currents, and upwelling."),
        _f("ocean.current_heat_transport", SF, "surface_cells", "K", "climate",
           dependencies=["ocean.currents", "ocean.mask", "atmosphere.seasonal_wind"],
           time_support="annual_diagnostic", fidelity_levels=["basin_gyre_proxy"],
           valid_range=[-10.0, 10.0], status=I,
           description="Ocean-current temperature anomaly proxy spread into adjacent coasts."),
        _f("ocean.upwelling", SF, "ocean_cells", "1", "climate",
           dependencies=["ocean.currents", "ocean.mask"],
           time_support="annual_diagnostic", fidelity_levels=["coastal_proxy"],
           valid_range=[0.0, 1.0], status=I,
           description="Eastern-boundary cold-current/upwelling proxy."),
        _f("ocean.basin_id", SF, "surface_cells", "1", "climate",
           dependencies=["ocean.mask"], time_support="static_geography",
           fidelity_levels=["graph_components"], status=I,
           description="Connected ocean-basin component id shared by terrain and climate; land cells are -1."),
        _f("ocean.solved_mask", SF, "surface_cells", "1", "climate",
           dependencies=["ocean.mask"], time_support="diagnostic_snapshot",
           fidelity_levels=["threshold_snapshot"], valid_range=[0.0, 1.0], status=I,
           description="Ocean mask used for the most recent climate solve."),
        _f("ocean.shelf_index", SF, "surface_cells", "1", "climate",
           dependencies=["ocean.mask", "terrain.elevation_m"],
           time_support="static_geography", fidelity_levels=["bathymetry_graph_proxy"],
           valid_range=[0.0, 1.0], status=I,
           description="Broad shelf/slope diagnostic from depth and distance to land."),
        _f("ocean.strait_index", SF, "surface_cells", "1", "climate",
           dependencies=["ocean.mask", "ocean.shelf_index"],
           time_support="static_geography", fidelity_levels=["narrow_gateway_proxy"],
           valid_range=[0.0, 1.0], status=I,
           description="Narrow ocean-gateway and exchange bottleneck diagnostic."),
        _f("terrain.barrier_index", SF, "surface_cells", "1", "climate",
           dependencies=["terrain.elevation_m"], time_support="static_geography",
           fidelity_levels=["climate_scale_relief"], valid_range=[0.0, 1.0],
           status=I, description="Mountain/highland barrier strength for winds and moisture."),
        _f("terrain.wind_gap_index", SF, "surface_cells", "1", "climate",
           dependencies=["terrain.barrier_index", "terrain.elevation_m"],
           time_support="static_geography", fidelity_levels=["climate_scale_relief"],
           valid_range=[0.0, 1.0], status=I,
           description="Low passes and corridors through climate-scale barriers."),
        _f("climate.continents", OBJ, "surface_cells", "1", "climate",
           dependencies=["climate.continent_id"], fidelity_levels=["component_objects"],
           status=I, description="Connected landmass objects for coupled climate."),
        _f("ocean.basins", OBJ, "surface_cells", "1", "climate",
           dependencies=["ocean.basin_id"], fidelity_levels=["component_objects"],
           status=I, description="Connected ocean-basin objects for coupled climate."),
        _f("ocean.margins", OBJ, "surface_cells", "1", "terrain",
           dependencies=["ocean.margin_type", "ocean.depth_province"],
           fidelity_levels=["component_objects"], status=I,
           description="Continental and oceanic margin objects with shelf/trench summaries."),
        _f("ocean.gateways", OBJ, "surface_cells", "1", "terrain",
           dependencies=["ocean.gateway_id", "tectonics.ocean_gateways"],
           fidelity_levels=["component_objects"], status=I,
           description="Restricted-ocean and strait/gateway objects with basin and Wilson-cycle context."),
        _f("ocean.gateway_systems", OBJ, "surface_cells", "1", "terrain",
           dependencies=["ocean.gateway_system_id", "ocean.gateways", "tectonics.ocean_gateways"],
           fidelity_levels=["regional_gateway_systems"], status=I,
           description="Grouped seaway, remnant-ocean, back-arc, and relict-sea systems for downstream climate."),
        _f("climate.coastline_segments", OBJ, "surface_cells", "1", "climate",
           dependencies=["climate.continent_id", "ocean.basin_id"],
           fidelity_levels=["component_pairs"], status=I,
           description="Continent-basin coastline segment summaries."),
        _f("ocean.straits", OBJ, "surface_cells", "1", "climate",
           dependencies=["ocean.strait_index"], fidelity_levels=["component_objects"],
           status=I, description="Narrow ocean gateway component summaries."),
        _f("terrain.barrier_belts", OBJ, "surface_cells", "1", "climate",
           dependencies=["terrain.barrier_index"], fidelity_levels=["component_objects"],
           status=I, description="Major climate-scale terrain barrier belt summaries."),
        _f("atmosphere.pressure_centers", OBJ, "season_surface_cells", "1",
           "climate",
           dependencies=["atmosphere.pressure_center_support",
                         "atmosphere.pressure_center_id",
                         "atmosphere.stationary_wave_pressure_support"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["seasonal_pressure_center_objects"], status=I,
           description="Seasonal pressure high/low center objects for R2a map-read attribution."),
        _f("climate.hydroclimate_regions", OBJ, "surface_cells", "1", "climate",
           dependencies=["climate.monsoon_rainfall_corridor",
                         "climate.storm_track_rainfall_corridor",
                         "climate.rain_shadow_index",
                         "climate.regional_precipitation_response"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["seasonal_region_objects"], status=I,
           description="Seasonal monsoon, storm-track, rain-shadow, and regional precipitation-response objects."),
        _f("climate.precipitation_response_regions", OBJ,
           "season_surface_cells", "1", "climate",
           dependencies=["climate.precipitation_response_region_id",
                         "climate.moisture_flow_precipitation_response",
                         "climate.moisture_budget_region_id",
                         "atmosphere.moisture_source_basin_id",
                         "climate.moisture_flow_network_id",
                         "climate.seasonal_precipitation"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["precipitation_response_region_objects"], status=I,
           description="C4j final wet/dry precipitation-response regions with source basin, budget region, and moisture-flow network attribution."),
        _f("climate.receiver_catchments", OBJ,
           "season_surface_cells", "1", "climate",
           dependencies=["climate.receiver_catchment_id",
                         "climate.source_basin_supply_index",
                         "climate.receiver_catchment_supply_balance",
                         "climate.receiver_supply_precipitation_feedback",
                         "climate.precipitation_response_region_id",
                         "climate.moisture_budget_region_id",
                         "atmosphere.moisture_source_basin_id",
                         "climate.moisture_flow_network_id",
                         "climate.seasonal_precipitation"],
           time_support="seasonal_diagnostic",
           fidelity_levels=["receiver_catchment_objects"], status=I,
           description="C4k receiver catchment object archive for source-basin to receiver-side water-budget closure diagnostics."),
        _f("ocean.salinity", SF, "ocean_cells", "g kg^-1", "climate",
           dependencies=["climate.evaporation", "climate.runoff"],
           conservation_constraints=["salt"], fidelity_levels=["box"], status=R),
        _f("cryosphere.sea_ice", SF, "ocean_cells", "1", "climate",
           dependencies=["climate.surface_temperature"],
           fidelity_levels=["threshold"], valid_range=[0.0, 1.0], status=I),
        _f("cryosphere.seasonal_sea_ice", SF, "season_surface_cells", "1",
           "climate",
           dependencies=["climate.seasonal_sst", "climate.ocean_heat_flux",
                         "ocean.mask"],
           time_support="seasonal_climatology",
           fidelity_levels=["bounded_cryosphere_feedback_proxy"],
           valid_range=[0.0, 1.0], status=I,
           description="Four-season sea-ice fraction derived from the raw cold ocean solution before exported SST freezing-floor clipping."),
        _f("cryosphere.seasonal_snow", SF, "season_surface_cells", "1",
           "climate",
           dependencies=["climate.seasonal_temperature",
                         "climate.seasonal_precipitation", "ocean.mask"],
           time_support="seasonal_climatology",
           fidelity_levels=["bounded_cryosphere_feedback_proxy"],
           valid_range=[0.0, 1.0], status=I,
           description="Four-season land snow persistence proxy from freezing temperature and available precipitation."),
        _f("cryosphere.snow_persistence", SF, "surface_cells", "1", "climate",
           dependencies=["cryosphere.seasonal_snow"],
           time_support="annual_diagnostic",
           fidelity_levels=["bounded_cryosphere_feedback_proxy"],
           valid_range=[0.0, 1.0], status=I,
           description="Annual persistent land-snow proxy aggregated from seasonal snow."),
        _f("cryosphere.ice_sheet", SF, "surface_cells", "m", "climate",
           dependencies=["climate.surface_temperature", "climate.precipitation"],
           conservation_constraints=["water"], fidelity_levels=["threshold", "flow"],
           valid_range=[0.0, 5000.0], status=I),

        # ---------------- biogeochemistry ----------------
        _f("biogeochem.carbon", GS, "global", "mol", "biogeochem",
           dependencies=["interior.degassing_co2", "climate.surface_temperature",
                         "biosphere.npp"],
           conservation_constraints=["carbon"], fidelity_levels=["copse_box", "cgenie"],
           status=I, validation="carbon inventory conserved across reservoirs"),
        _f("biogeochem.oxygen", GS, "global", "mol", "biogeochem",
           dependencies=["biosphere.npp", "biogeochem.carbon"],
           conservation_constraints=["oxygen"], fidelity_levels=["box"], status=I,
           description="Atmospheric O2 from organic carbon burial vs oxidative sinks."),
        _f("biogeochem.phosphorus", GS, "global", "mol", "biogeochem",
           conservation_constraints=["phosphorus"], fidelity_levels=["box"], status=R),
        _f("biogeochem.ocean_redox", SF, "ocean_cells", "1", "biogeochem",
           dependencies=["biogeochem.oxygen", "biosphere.npp"],
           fidelity_levels=["box"], status=R,
           description="Oxic/anoxic/euxinic state (drives black shales, anoxic events)."),
        _f("biogeochem.weathering_flux", GS, "global", "mol Myr^-1", "biogeochem",
           dependencies=["climate.surface_temperature", "climate.runoff",
                         "terrain.elevation_m"],
           conservation_constraints=["carbon"], fidelity_levels=["parametric"], status=I,
           description="Carbonate-silicate weathering CO2 drawdown."),

        # ---------------- biosphere ----------------
        _f("biosphere.functional_groups", OBJ, "global", "1", "biosphere",
           fidelity_levels=["niche"], status=I,
           description="Functional groups described by traits, not species lists."),
        _f("biosphere.lineages", OBJ, "global", "1", "biosphere",
           dependencies=["biosphere.functional_groups"], fidelity_levels=["tree"], status=I,
           description="Phylogeny with innovation & extinction history."),
        _f("biosphere.biome", SF, "surface_cells", "1", "biosphere",
           dependencies=["climate.surface_temperature", "climate.precipitation",
                         "climate.seasonal_temperature",
                         "climate.seasonal_precipitation",
                         "biosphere.npp"],
           fidelity_levels=["classified"], status=I),
        _f("biosphere.vegetation_climate_feedback", SF, "surface_cells", "1",
           "biosphere",
           dependencies=["climate.seasonal_temperature",
                         "climate.seasonal_precipitation",
                         "atmosphere.moisture_access",
                         "cryosphere.snow_persistence"],
           time_support="annual_diagnostic",
           fidelity_levels=["bounded_vegetation_feedback_proxy"],
           valid_range=[0.0, 1.0], status=I,
           description="Potential vegetation albedo/evapotranspiration feedback proxy kept bounded for C5 climate-biosphere coupling diagnostics."),
        _f("biosphere.npp", SF, "surface_cells", "kg m^-2 yr^-1", "biosphere",
           dependencies=["climate.surface_temperature", "climate.precipitation",
                         "stellar.surface_flux", "biogeochem.oxygen"],
           conservation_constraints=["carbon"], fidelity_levels=["empirical"],
           valid_range=[0.0, 5.0], status=I,
           description="Net primary productivity."),
        _f("biosphere.distribution", SF, "surface_cells", "1", "biosphere",
           dependencies=["biosphere.functional_groups", "biosphere.biome"],
           fidelity_levels=["niche_dispersal"], status=I,
           description="Group occupancy constrained by niche AND dispersal/isolation."),

        # ---------------- resources ----------------
        _f("resources.deposits", OBJ, "surface_cells", "1", "resources",
           dependencies=["tectonics.volcanoes", "terrain.lithology",
                         "biogeochem.ocean_redox", "sediment.thickness_m"],
           fidelity_levels=["genesis_rules", "probabilistic"], status=I,
           validation="every deposit has genesis model, age, host, grade, preservation",
           description="Ore/energy deposits as objects with full genesis-preservation history."),

        # ---------------- geological archive ----------------
        _f("archive.strata", OBJ, "surface_cells", "1", "terrain",
           dependencies=["sediment.thickness_m"], fidelity_levels=["layer_cake"], status=R),
        _f("archive.fossil_potential", SF, "surface_cells", "1", "biosphere",
           dependencies=["biosphere.npp", "sediment.thickness_m"],
           fidelity_levels=["empirical"], status=R),
    ])
    return reg
